### ISSUE TITLE
Can't get it to install

### ISSUE THREAD

**Issue by ellev** [danielreiser/Homebridge-Simple-Garage-Door-Opener#7]
Please help me. I had it running on my previous install but my card crashed and now with the new versions I can't get it installed it ends with this: make: *** [rpio.target.mk:110: Release/obj.target/rpio/src/rpio.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.118-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpio@0.9.23 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rpio@0.9.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-29T22_42_15_281Z-debug.log

**Comment by stodla123** [comment]
same problem here cannot install it. please help. 

root@homebridge:/home/pi# npm install homebridge-simple-garage-door-opener -g

> rpio@0.9.23 install /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.18.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio/.node-gyp'
gyp ERR! System Linux 4.19.118+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpio@0.9.23 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpio@0.9.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-18T15_03_40_445Z-debug.log




root@homebridge:/home/pi# cat /root/.npm/_logs/2020-07-18T15_03_40_445Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'homebridge-simple-garage-door-opener',
1 verbose cli   '-g'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.0
4 verbose npm-session e58d1e6c94259851
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-simple-garage-door-opener 2404ms (from cache)
8 silly pacote tag manifest for homebridge-simple-garage-door-opener@latest fetched in 2687ms
9 timing stage:loadCurrentTree Completed in 3109ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 7ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 49ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-simple-garage-door-opener@1.0.5 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/rpio 586ms (from cache)
18 silly pacote range manifest for rpio@^0.9.13 fetched in 703ms
19 silly resolveWithNewModule rpio@0.9.23 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/bindings 1018ms (from cache)
21 silly pacote range manifest for bindings@* fetched in 1136ms
22 silly resolveWithNewModule bindings@1.5.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/nan 1225ms (from cache)
24 silly pacote range manifest for nan@* fetched in 1359ms
25 silly resolveWithNewModule nan@2.14.1 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 401ms (from cache)
27 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 450ms
28 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
29 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2899ms
30 timing stage:loadIdealTree Completed in 3034ms
31 silly currentTree lib
32 silly idealTree lib
32 silly idealTree └─┬ homebridge-simple-garage-door-opener@1.0.5
32 silly idealTree   ├── bindings@1.5.0
32 silly idealTree   ├── file-uri-to-path@1.0.0
32 silly idealTree   ├── nan@2.14.1
32 silly idealTree   └── rpio@0.9.23
33 silly install generateActionsToTake
34 timing stage:generateActionsToTake Completed in 168ms
35 silly diffTrees action count 5
36 silly diffTrees add file-uri-to-path@1.0.0
37 silly diffTrees add bindings@1.5.0
38 silly diffTrees add nan@2.14.1
39 silly diffTrees add rpio@0.9.23
40 silly diffTrees add homebridge-simple-garage-door-opener@1.0.5
41 silly decomposeActions action count 40
42 silly decomposeActions fetch file-uri-to-path@1.0.0
43 silly decomposeActions extract file-uri-to-path@1.0.0
44 silly decomposeActions preinstall file-uri-to-path@1.0.0
45 silly decomposeActions build file-uri-to-path@1.0.0
46 silly decomposeActions install file-uri-to-path@1.0.0
47 silly decomposeActions postinstall file-uri-to-path@1.0.0
48 silly decomposeActions finalize file-uri-to-path@1.0.0
49 silly decomposeActions refresh-package-json file-uri-to-path@1.0.0
50 silly decomposeActions fetch bindings@1.5.0
51 silly decomposeActions extract bindings@1.5.0
52 silly decomposeActions preinstall bindings@1.5.0
53 silly decomposeActions build bindings@1.5.0
54 silly decomposeActions install bindings@1.5.0
55 silly decomposeActions postinstall bindings@1.5.0
56 silly decomposeActions finalize bindings@1.5.0
57 silly decomposeActions refresh-package-json bindings@1.5.0
58 silly decomposeActions fetch nan@2.14.1
59 silly decomposeActions extract nan@2.14.1
60 silly decomposeActions preinstall nan@2.14.1
61 silly decomposeActions build nan@2.14.1
62 silly decomposeActions install nan@2.14.1
63 silly decomposeActions postinstall nan@2.14.1
64 silly decomposeActions finalize nan@2.14.1
65 silly decomposeActions refresh-package-json nan@2.14.1
66 silly decomposeActions fetch rpio@0.9.23
67 silly decomposeActions extract rpio@0.9.23
68 silly decomposeActions preinstall rpio@0.9.23
69 silly decomposeActions build rpio@0.9.23
70 silly decomposeActions install rpio@0.9.23
71 silly decomposeActions postinstall rpio@0.9.23
72 silly decomposeActions finalize rpio@0.9.23
73 silly decomposeActions refresh-package-json rpio@0.9.23
74 silly decomposeActions fetch homebridge-simple-garage-door-opener@1.0.5
75 silly decomposeActions extract homebridge-simple-garage-door-opener@1.0.5
76 silly decomposeActions preinstall homebridge-simple-garage-door-opener@1.0.5
77 silly decomposeActions build homebridge-simple-garage-door-opener@1.0.5
78 silly decomposeActions install homebridge-simple-garage-door-opener@1.0.5
79 silly decomposeActions postinstall homebridge-simple-garage-door-opener@1.0.5
80 silly decomposeActions finalize homebridge-simple-garage-door-opener@1.0.5
81 silly decomposeActions refresh-package-json homebridge-simple-garage-door-opener@1.0.5
82 silly install executeActions
83 silly doSerial global-install 40
84 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
85 verbose lock using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
86 silly doParallel extract 5
87 silly extract file-uri-to-path@1.0.0
88 silly extract bindings@1.5.0
89 silly extract nan@2.14.1
90 silly extract rpio@0.9.23
91 silly extract homebridge-simple-garage-door-opener@1.0.5
92 silly tarball trying file-uri-to-path@1.0.0 by hash: sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==
93 silly tarball trying bindings@* by hash: sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==
94 silly tarball trying nan@* by hash: sha512-isWHgVjnFjh2x2yuJ/tj3JbwoHu3UC2dX5G/88Cm24yB6YopVgxvBObDY7n5xW6ExmFhJpSEQqFPvq9zaXc8Jw==
95 silly tarball trying rpio@^0.9.13 by hash: sha512-Cbx/Bo9eoPOzNg8XIZq5nzU8ryqm1ckUPPEynAdhoemBzydyE7fKeE16cjpF8a4Gfcd3JCgDsW1bGIvO1cxE1Q==
96 silly tarball trying homebridge-simple-garage-door-opener@latest by hash: sha1-7W+oyuvInhc7r5xX3e7Nw5PjlVs=
97 silly extract bindings@* extracted to /usr/local/lib/node_modules/.staging/bindings-52fe6661 (1663ms)
98 silly extract homebridge-simple-garage-door-opener@latest extracted to /usr/local/lib/node_modules/.staging/homebridge-simple-garage-door-opener-2754552f (1704ms)
99 silly extract file-uri-to-path@1.0.0 extracted to /usr/local/lib/node_modules/.staging/file-uri-to-path-e67ca30a (1797ms)
100 silly extract rpio@^0.9.13 extracted to /usr/local/lib/node_modules/.staging/rpio-8b559921 (1986ms)
101 silly extract nan@* extracted to /usr/local/lib/node_modules/.staging/nan-1c73cf2d (2250ms)
102 timing action:extract Completed in 2314ms
103 silly doReverseSerial unbuild 40
104 silly doSerial remove 40
105 silly doSerial move 40
106 silly doSerial finalize 40
107 silly finalize /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/file-uri-to-path
108 silly finalize /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/bindings
109 silly finalize /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/nan
110 silly finalize /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio
111 silly finalize /usr/local/lib/node_modules/homebridge-simple-garage-door-opener
112 timing action:finalize Completed in 642ms
113 silly doParallel refresh-package-json 5
114 silly refresh-package-json /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/file-uri-to-path
115 silly refresh-package-json /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/bindings
116 silly refresh-package-json /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/nan
117 silly refresh-package-json /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio
118 silly refresh-package-json /usr/local/lib/node_modules/homebridge-simple-garage-door-opener
119 timing action:refresh-package-json Completed in 722ms
120 silly doParallel preinstall 5
121 silly preinstall file-uri-to-path@1.0.0
122 info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
123 silly preinstall bindings@1.5.0
124 info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
125 silly preinstall nan@2.14.1
126 info lifecycle nan@2.14.1~preinstall: nan@2.14.1
127 silly preinstall rpio@0.9.23
128 info lifecycle rpio@0.9.23~preinstall: rpio@0.9.23
129 silly preinstall homebridge-simple-garage-door-opener@1.0.5
130 info lifecycle homebridge-simple-garage-door-opener@1.0.5~preinstall: homebridge-simple-garage-door-opener@1.0.5
131 timing action:preinstall Completed in 67ms
132 silly doSerial build 40
133 silly build file-uri-to-path@1.0.0
134 info linkStuff file-uri-to-path@1.0.0
135 silly linkStuff file-uri-to-path@1.0.0 has /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules as its parent node_modules
136 silly linkStuff file-uri-to-path@1.0.0 is part of a global install
137 silly linkStuff file-uri-to-path@1.0.0 is installed into a global node_modules
138 silly build bindings@1.5.0
139 info linkStuff bindings@1.5.0
140 silly linkStuff bindings@1.5.0 has /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules as its parent node_modules
141 silly linkStuff bindings@1.5.0 is part of a global install
142 silly linkStuff bindings@1.5.0 is installed into a global node_modules
143 silly build nan@2.14.1
144 info linkStuff nan@2.14.1
145 silly linkStuff nan@2.14.1 has /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules as its parent node_modules
146 silly linkStuff nan@2.14.1 is part of a global install
147 silly linkStuff nan@2.14.1 is installed into a global node_modules
148 silly build rpio@0.9.23
149 info linkStuff rpio@0.9.23
150 silly linkStuff rpio@0.9.23 has /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules as its parent node_modules
151 silly linkStuff rpio@0.9.23 is part of a global install
152 silly linkStuff rpio@0.9.23 is installed into a global node_modules
153 silly build homebridge-simple-garage-door-opener@1.0.5
154 info linkStuff homebridge-simple-garage-door-opener@1.0.5
155 silly linkStuff homebridge-simple-garage-door-opener@1.0.5 has /usr/local/lib/node_modules as its parent node_modules
156 silly linkStuff homebridge-simple-garage-door-opener@1.0.5 is part of a global install
157 silly linkStuff homebridge-simple-garage-door-opener@1.0.5 is installed into a global node_modules
158 silly linkStuff homebridge-simple-garage-door-opener@1.0.5 is installed into the top-level global node_modules
159 timing action:build Completed in 59ms
160 silly doSerial global-link 40
161 silly doParallel update-linked 0
162 silly doSerial install 40
163 silly install file-uri-to-path@1.0.0
164 info lifecycle file-uri-to-path@1.0.0~install: file-uri-to-path@1.0.0
165 silly install bindings@1.5.0
166 info lifecycle bindings@1.5.0~install: bindings@1.5.0
167 silly install nan@2.14.1
168 info lifecycle nan@2.14.1~install: nan@2.14.1
169 silly install rpio@0.9.23
170 info lifecycle rpio@0.9.23~install: rpio@0.9.23
171 verbose lifecycle rpio@0.9.23~install: unsafe-perm in lifecycle false
172 verbose lifecycle rpio@0.9.23~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio/node_modules/.bin:/usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
173 verbose lifecycle rpio@0.9.23~install: CWD: /usr/local/lib/node_modules/homebridge-simple-garage-door-opener/node_modules/rpio
174 silly lifecycle rpio@0.9.23~install: Args: [ '-c', 'node-gyp rebuild' ]
175 silly lifecycle rpio@0.9.23~install: Returned: code: 1  signal: null
176 info lifecycle rpio@0.9.23~install: Failed to exec install script
177 timing action:install Completed in 10775ms
178 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
179 timing stage:rollbackFailedOptional Completed in 896ms
180 timing stage:runTopLevelLifecycles Completed in 22118ms
181 verbose stack Error: rpio@0.9.23 install: `node-gyp rebuild`
181 verbose stack Exit status 1
181 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
181 verbose stack     at EventEmitter.emit (events.js:315:20)
181 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
181 verbose stack     at ChildProcess.emit (events.js:315:20)
181 verbose stack     at maybeClose (internal/child_process.js:1021:16)
181 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
182 verbose pkgid rpio@0.9.23
183 verbose cwd /home/pi
184 verbose Linux 4.19.118+
185 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "homebridge-simple-garage-door-opener" "-g"
186 verbose node v12.18.0
187 verbose npm  v6.14.5
188 error code ELIFECYCLE
189 error errno 1
190 error rpio@0.9.23 install: `node-gyp rebuild`
190 error Exit status 1
191 error Failed at the rpio@0.9.23 install script.
191 error This is probably not a problem with npm. There is likely additional logging output above.
192 verbose exit [ 1, true ]

**Comment by beeper99** [comment]
yep same here, I guess this is too old.
